name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '22'
      - run: npm install --legacy-peer-deps
      - run: npm run lint
      - run: npm run lint:exports
      - run: npm run format:check
      - run: npm run test
      - run: npm run typecheck
      - run: npm run build-extension
      - run: npm audit --audit-level=critical
